Import the numpy package under the name np

In [1]:
import numpy as np


Print the numpy version and the configuration

In [2]:
import numpy as np

print("Numpy Version:", np.__version__)
print("Numpy Configuration:")
print(np.show_config())


Numpy Version: 1.26.2
Numpy Configuration:
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30153",
      "commands": "cl.exe"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.0",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30153",
      "commands": "cl.exe"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "mkl-sdl",
      "found": true,
      "version": "2023.1",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/Administrator/miniconda3/envs/arewadatascience/Library/include",
      "lib directory": "C:/Use

c:\Users\Administrator\miniconda3\envs\arewadatascience\Lib\site-packages\numpy\__config__.py:149: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


Create a null vector of size 10

In [4]:
import numpy as np

n_vector = np.zeros(10)
print(n_vector)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


How to find the memory size of any array

In [5]:
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Find the memory size
memory_size = arr.nbytes

print("Memory size of the array:", memory_size, "bytes")


Memory size of the array: 20 bytes


How to get the documentation of the numpy add function from the command line?

Create a null vector of size 10 but the fifth value which is 1

In [6]:
import numpy as np

null_vector = np.zeros(10)
null_vector[4] = 1

print(null_vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Create a vector with values ranging from 10 to 49

In [7]:
import numpy as np

vector = np.arange(10, 50)
print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


 Reverse a vector (first element becomes last)

In [8]:
reversed_vector = vector[::-1]
print(reversed_vector)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
import numpy as np

matrix = np.arange(9).reshape(3, 3)
print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


Find indices of non-zero elements from [1,2,0,0,4,0]

In [2]:
import numpy as np

'''arr=np.array([1,2,0,0,4,0])
print("Elements of array arr is:",arr )
print("Is array arr contains non-zero elements:" ,np.any(arr))'''

arr=np.array([1,2,0,0,4,0])
print("Elements of array arr is:",arr )
No_zero_ele =np.nonzero(arr)
print("Non-zero elements of the array arr:",arr[np.nonzero(arr)])
print("indices non-zero elements of array arr:",No_zero_ele )

Elements of array arr is: [1 2 0 0 4 0]
Non-zero elements of the array arr: [1 2 4]
indices non-zero elements of array arr: (array([0, 1, 4], dtype=int64),)


Create a 3x3 identity matrix

In [3]:
import numpy as np

i_matrix = np.eye(3)
print(i_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Create a 3x3x3 array with random values

In [5]:
import numpy as np

arr = np.random.rand(3, 3, 3)
print(arr)


[[[0.12693413 0.49381772 0.04902207]
  [0.14062798 0.43269522 0.58320315]
  [0.92643806 0.97569955 0.51996709]]

 [[0.69411651 0.55679996 0.65688005]
  [0.84072972 0.76573622 0.38932305]
  [0.74551745 0.77215531 0.61292318]]

 [[0.16976265 0.06451953 0.67512418]
  [0.43375784 0.72108509 0.83981372]
  [0.16351687 0.53004099 0.34410989]]]


Create a 10x10 array with random values and find the minimum and maximum values

In [8]:
import numpy as np

# Create a 10x10 array with random values
arr = np.random.rand(10, 10)
print(arr)

# Find the minimum and maximum values
min_value = np.min(arr)
max_value = np.max(arr)

print("Minimum value:", min_value)
print("Maximum value:", max_value)


[[0.30526894 0.11639061 0.63892729 0.84632996 0.04858464 0.78900305
  0.55692008 0.87444174 0.03702647 0.89019205]
 [0.33570597 0.79614245 0.90859058 0.43514676 0.97324435 0.76157976
  0.09068936 0.22616824 0.89306922 0.77791367]
 [0.20767048 0.74043809 0.59123003 0.65211408 0.47519938 0.23625395
  0.60022452 0.56525003 0.04564811 0.01744112]
 [0.43761889 0.91169507 0.64375808 0.18724672 0.9960855  0.56424763
  0.91261412 0.14024963 0.63456674 0.09960344]
 [0.24756833 0.37806268 0.39446677 0.11076914 0.43354331 0.10507483
  0.0545226  0.70654062 0.89691784 0.10522198]
 [0.32738225 0.53747775 0.62625242 0.21709438 0.840725   0.8490383
  0.68669582 0.96042351 0.65909543 0.18841251]
 [0.43832431 0.76557281 0.90722116 0.55625866 0.28481037 0.48324952
  0.30190915 0.48695104 0.94117468 0.66853657]
 [0.98927147 0.54239301 0.89316984 0.02664668 0.81505523 0.97901721
  0.12080957 0.50349604 0.68600126 0.22699601]
 [0.64869657 0.66650226 0.0409895  0.23673672 0.85679195 0.62440313
  0.85946891 

Create a random vector of size 30 and find the mean value

In [9]:
import numpy as np

# Create a random vector of size 30
random_vector = np.random.rand(30)

# Find the mean value
mean_value = np.mean(random_vector)

print("Mean value:", mean_value)


Mean value: 0.49129532652075386


15. Create a 2d array with 1 on the border and 0 inside

In [31]:
import numpy as np


arr = np.ones((5,5))
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

print(arr)


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


16. How to add a border (filled with 0's) around an existing array?

In [33]:
import numpy as np

# Existing array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Add border filled with 0's
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

print(arr)


[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


17. What is the result of the following expression?

In [37]:
import numpy as np
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [45]:
import numpy as np

m = np.diag([1, 2, 3, 4], k=-1)
print(m)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


Create a 8x8 matrix and fill it with a checkerboard pattern

In [48]:
import numpy as np

mt = np.zeros((8, 8))
mt[1::2, ::2] = 1
mt[::2, 1::2] = 1

print(mt)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [49]:
import numpy as np

shape = (6, 7, 8)
index_100 = np.unravel_index(99, shape)

print("Index (x, y, z) of the 100th element:", index_100)


Index (x, y, z) of the 100th element: (1, 5, 3)


Create a checkerboard 8x8 matrix using the tile function

In [53]:
import numpy as np


tile = np.array([[0, 1], [1, 0]])
cb = np.tile(tile, (4, 4))

print(cb)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Normalize a 5x5 random matrix

In [3]:
from sklearn.preprocessing import normalize
import numpy as np

# Create a 5x5 random matrix
matrix = np.random.rand(5, 5)

# Normalize the matrix
normalized_matrix = normalize(matrix)

print(normalized_matrix)


[[0.75660908 0.43914236 0.16413115 0.13390694 0.43569093]
 [0.51145843 0.4040846  0.59026309 0.44783991 0.16172449]
 [0.42105228 0.3640624  0.5457537  0.59907741 0.18284612]
 [0.6047449  0.09698108 0.34175996 0.50622042 0.50181599]
 [0.12699218 0.69766917 0.43548413 0.39209633 0.39210299]]


Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [3]:
import numpy as np

# Create the custom dtype
color_dtype = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])

# Example usage
color = np.array([(255, 0, 0, 255)], dtype=color_dtype)
print(color)


[(255, 0, 0, 255)]


24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [5]:
import numpy as np

mx1 = np.random.rand(5, 3)
mx2 = np.random.rand(3, 2)
result = np.dot(mx1, mx2)

print(result)


[[1.42617001 1.24193318]
 [1.34788184 1.47911396]
 [1.34292602 1.19240974]
 [0.46256623 0.50611363]
 [1.06061382 1.24235962]]


25. Given a 1D array, negate all elements which are between 3 and 8, in place

In [10]:
import numpy as np


arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr[(arr > 3) & (arr < 8)] *= -1

print(arr)


[ 1  2  3 -4 -5 -6 -7  8  9 10]


In [11]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


27. Consider an integer vector Z, which of these expressions are legal?.\
Z**Z.\
2 << Z >> 2.\
Z <- Z.\
1j*Z.\
Z/1/1.\
Z<Z>Z

'''The following expressions are not legal:.\

2 << Z >> 2: The left shift and right shift operators (<< and >>) are not defined for arrays or vectors..\
1j * Z: The complex multiplication operator (*) is not defined for arrays or vectors.'''

1.  What are the result of the following expressions?.\
np.array(0) / np.array(0).\
np.array(0) // np.array(0).\
np.array([np.nan]).astype(int).astype(float)

In [3]:
import numpy as np

print('The result of the expressions are:')
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

The result of the expressions are:


C:\Users\Administrator\AppData\Local\Temp\ipykernel_10476\2426853172.py:4: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_10476\2426853172.py:5: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_10476\2426853172.py:6: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])

29. How to round away from zero a float array ?

In [5]:
import numpy as np

f_array = np.array([-1.5, -1.2, -0.8, 0.8, 1.2, 1.5])
r_array = np.ceil(f_array)

print(r_array)


[-1. -1. -0.  1.  2.  2.]


30. How to find common values between two arrays?

In [6]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])
common_values = np.intersect1d(array1, array2)

print("Common values:", common_values)


Common values: [4 5]


1.  Is the following expressions true?.\
np.sqrt(-1) == np.emath.sqrt(-1)

In [8]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_10476\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

33. How to get the dates of yesterday, today and tomorrow?

In [9]:
import datetime

# Get today's date
today = datetime.date.today()

# Get yesterday's date
yesterday = today - datetime.timedelta(days=1)

# Get tomorrow's date
tomorrow = today + datetime.timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2024-02-07
Today: 2024-02-08
Tomorrow: 2024-02-09


34. How to get all the dates corresponding to the month of July 2016?

In [10]:
import pandas as pd

# Create a date range for the month of July 2016
dates = pd.date_range(start='2016-07-01', end='2016-07-31')

print(dates)


DatetimeIndex(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
               '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
               '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
               '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
               '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
               '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
               '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
               '2016-07-29', '2016-07-30', '2016-07-31'],
              dtype='datetime64[ns]', freq='D')


36. Extract the integer part of a random array of positive numbers using 4 different methods

In [20]:
import numpy as np

# Create a random array of positive numbers
random_array = np.random.rand(5) * 10

# Extract the integer part using astype() method
integer_part = random_array.astype(int)

print(integer_part)


[3 8 4 0 3]


In [19]:
import numpy as np

# Create a random array of positive numbers
random_array = np.random.rand(5) * 10

# Extract the integer part using the floor method
integer_part = np.floor(random_array)

print(integer_part)


[0. 1. 4. 1. 8.]


In [21]:
import numpy as np

# Create a random array of positive numbers
random_array = np.random.rand(5) * 10

# Extract the integer part using the trunc function
integer_part = np.trunc(random_array)

print(integer_part)



[0. 4. 3. 8. 2.]


In [22]:
import numpy as np

# Create a random array of positive numbers
random_array = np.random.rand(5) * 10

# Extract the integer part using np.int function
integer_part = np.int_(random_array)

print(integer_part)


[1 1 5 8 8]


37. Create a 5x5 matrix with row values ranging from 0 to 4

In [23]:
import numpy as np

matrix = np.tile(np.arange(5), (5, 1))
print(matrix)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


38. Consider a generator function that generates 10 integers and use it to build an array

In [24]:
import numpy as np

# Define the generator function
def generate_integers():
    for i in range(10):
        yield i

# Build an array using the generator function
array = np.fromiter(generate_integers(), dtype=int)

print(array)


[0 1 2 3 4 5 6 7 8 9]


39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [28]:
import numpy as np

vector = np.linspace(0, 1, 12)[1:-1]
print(vector)


[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


40. Create a random vector of size 10 and sort it

In [29]:
import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

# Sort the vector
sorted_vector = np.sort(random_vector)

print(sorted_vector)


[0.08054443 0.18523198 0.38139533 0.38690612 0.44043328 0.48004155
 0.60746102 0.82010404 0.82664286 0.88184955]


How to sum a small array faster than np.sum?

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
sum_result = sum(arr)

print("Sum:", sum_result)


Sum: 15


42. Consider two random array A and B, check if they are equal

In [2]:
import numpy as np

# Create two random arrays
A = np.random.rand(5)
B = np.random.rand(5)

# Check if the arrays are equal
equal = np.array_equal(A, B)

print("Are the arrays equal?", equal)


Are the arrays equal? False


43. Make an array immutable (read-only)

In [7]:
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Make the array read-only
arr.flags.writeable = False

# Try to modify the array (will raise an error)
arr[0] = 10


44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [8]:
import numpy as np

# Create a random 10x2 matrix representing cartesian coordinates
cartesian_coords = np.random.rand(10, 2)

# Convert cartesian coordinates to polar coordinates
x = cartesian_coords[:, 0]
y = cartesian_coords[:, 1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)

# Create a 10x2 matrix representing polar coordinates
polar_coords = np.column_stack((r, theta))

print("Cartesian Coordinates:")
print(cartesian_coords)
print("\nPolar Coordinates:")
print(polar_coords)


Cartesian Coordinates:
[[0.03860662 0.57961299]
 [0.51768089 0.19846126]
 [0.04857541 0.56912631]
 [0.94411919 0.1555117 ]
 [0.93782122 0.56062358]
 [0.20349283 0.93845465]
 [0.07333724 0.55350739]
 [0.94599581 0.33043552]
 [0.70775503 0.22946506]
 [0.36571109 0.59332849]]

Polar Coordinates:
[[0.58089732 1.50428698]
 [0.55441896 0.36608501]
 [0.57119553 1.48565183]
 [0.95684112 0.1632503 ]
 [1.09261495 0.53879562]
 [0.96026375 1.35726383]
 [0.55834468 1.43906808]
 [1.00204576 0.33605031]
 [0.74402379 0.31352206]
 [0.69698156 1.01842547]]


45. Create random vector of size 10 and replace the maximum value by 0

In [10]:
import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

# Find the maximum value
max_value = np.max(random_vector)

# Replace the maximum value with 0
random_vector[random_vector == max_value] = 0

print(random_vector)


[0.40610465 0.47006855 0.08662248 0.         0.74982152 0.16660943
 0.04631832 0.61444527 0.8087169  0.36575479]


46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area

In [12]:
import numpy as np

# Create a structured array with x and y coordinates
coordinates = np.zeros((10,), dtype=[('x', float), ('y', float)])

# Generate x and y coordinates covering the [0,1]x[0,1] area
coordinates['x'] = np.linspace(0, 1, 10)
coordinates['y'] = np.linspace(0, 1, 10)

print(coordinates)


[(0.        , 0.        ) (0.11111111, 0.11111111)
 (0.22222222, 0.22222222) (0.33333333, 0.33333333)
 (0.44444444, 0.44444444) (0.55555556, 0.55555556)
 (0.66666667, 0.66666667) (0.77777778, 0.77777778)
 (0.88888889, 0.88888889) (1.        , 1.        )]


47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [13]:
import numpy as np

# Example arrays
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

# Construct the Cauchy matrix
C = 1 / (X[:, np.newaxis] - Y)

print(C)


[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


48. Print the minimum and maximum representable value for each numpy scalar type

In [ ]:
import numpy as np

# List of numpy scalar types
scalar_types = [np.bool_, np.int8, np.int16, np.int32, np.int64, np.uint8, np.uint16, np.uint32, np.uint64,
                np.float16, np.float32, np.float64, np.complex64, np.complex128]

# Iterate over the scalar types and print the minimum and maximum values
for scalar_type in scalar_types:
    min_value = np.iinfo(scalar_type).min if np.issubdtype(scalar_type, np.integer) else np.finfo(scalar_type).min
    max_value = np.iinfo(scalar_type).max if np.issubdtype(scalar_type, np.integer) else np.finfo(scalar_type).max
    print(f"{scalar_type.__name__}: Minimum = {min_value}, Maximum = {max_value}")


49. How to print all the values of an array?

In [16]:
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Print all the values of the array
print(arr)


[1 2 3 4 5]


50. How to find the closest value (to a given scalar) in a vector?

In [17]:
import numpy as np

# Given scalar
scalar = 3.5

# Vector
vector = np.array([1, 2, 3, 4, 5])

# Calculate the absolute difference
abs_diff = np.abs(vector - scalar)

# Find the index of the element with the smallest absolute difference
closest_index = np.argmin(abs_diff)

# Get the closest value
closest_value = vector[closest_index]

print("Closest value:", closest_value)


Closest value: 3


51. Create a structured array representing a position (x,y) and a color (r,g,b)

In [1]:
import numpy as np

# Define the structured array dtype
dtype = [('position', [('x', float), ('y', float)]), ('color', [('r', int), ('g', int), ('b', int)])]

# Create an empty structured array
structured_array = np.empty((1,), dtype=dtype)

# Set the values for position and color
structured_array['position']['x'] = 10.0
structured_array['position']['y'] = 20.0
structured_array['color']['r'] = 255
structured_array['color']['g'] = 0
structured_array['color']['b'] = 0

print(structured_array)


[((10., 20.), (255, 0, 0))]


52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances

In [2]:
import numpy as np
from scipy.spatial.distance import cdist

# Create a random vector with shape (100, 2)
random_vector = np.random.rand(100, 2)

# Calculate the point-by-point distances
distances = cdist(random_vector, random_vector)

print(distances)


[[0.         0.0492764  0.7449522  ... 0.80544518 0.35052027 0.35839322]
 [0.0492764  0.         0.75775074 ... 0.8187696  0.39765268 0.37928626]
 [0.7449522  0.75775074 0.         ... 0.06139577 0.84979649 0.3937896 ]
 ...
 [0.80544518 0.8187696  0.06139577 ... 0.         0.90106557 0.45263103]
 [0.35052027 0.39765268 0.84979649 ... 0.90106557 0.         0.48591936]
 [0.35839322 0.37928626 0.3937896  ... 0.45263103 0.48591936 0.        ]]


53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [3]:
import numpy as np

# Create a float (32 bits) array
float_array = np.array([1.5, 2.7, 3.9], dtype=np.float32)

# Convert the float array to an integer (32 bits) array in place
float_array = float_array.astype(np.int32)

print(float_array)


[1 2 3]


54.  How to read the following file? <br>
1, 2, 3, 4, 5 <br>
6,  ,  , 7, 8 <br>
 ,  , 9,10,11

In [ ]:
import pandas as pd

# Define the data as a string
data = '''1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11'''

# Read the data into a dataframe
df = pd.read_csv(pd.compat.StringIO(data), header=None)

print(df)


55. What is the equivalent of enumerate for numpy arrays?

In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

for index, value in np.ndenumerate(arr):
    print(index, value)


(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5


56. Generate a generic 2D Gaussian-like array

In [7]:
import numpy as np

# Define the size of the array
size = (10, 10)

# Create a grid of coordinates
x, y = np.meshgrid(np.linspace(-1, 1, size[0]), np.linspace(-1, 1, size[1]))

# Calculate the Gaussian-like values
sigma = 0.5
gaussian_array = np.exp(-(x**2 + y**2) / (2 * sigma**2))

print(gaussian_array)


[[0.01831564 0.0403616  0.07300087 0.10836802 0.13203459 0.13203459
  0.10836802 0.07300087 0.0403616  0.01831564]
 [0.0403616  0.08894358 0.16086971 0.2388072  0.29096046 0.29096046
  0.2388072  0.16086971 0.08894358 0.0403616 ]
 [0.07300087 0.16086971 0.29096046 0.43192377 0.52625189 0.52625189
  0.43192377 0.29096046 0.16086971 0.07300087]
 [0.10836802 0.2388072  0.43192377 0.64118039 0.7812082  0.7812082
  0.64118039 0.43192377 0.2388072  0.10836802]
 [0.13203459 0.29096046 0.52625189 0.7812082  0.95181678 0.95181678
  0.7812082  0.52625189 0.29096046 0.13203459]
 [0.13203459 0.29096046 0.52625189 0.7812082  0.95181678 0.95181678
  0.7812082  0.52625189 0.29096046 0.13203459]
 [0.10836802 0.2388072  0.43192377 0.64118039 0.7812082  0.7812082
  0.64118039 0.43192377 0.2388072  0.10836802]
 [0.07300087 0.16086971 0.29096046 0.43192377 0.52625189 0.52625189
  0.43192377 0.29096046 0.16086971 0.07300087]
 [0.0403616  0.08894358 0.16086971 0.2388072  0.29096046 0.29096046
  0.2388072  0

57. How to randomly place p elements in a 2D array?

In [1]:
import numpy as np

def randomly_place_elements(array, p, values):
    # Get the shape of the array
    shape = array.shape
    
    # Generate p random indices within the range of the array shape
    indices = np.random.choice(np.prod(shape), p, replace=False)
    
    # Assign the desired values to the randomly selected indices
    array.flat[indices] = values
    
    return array

# Example usage
shape = (5, 5)  # Shape of the 2D array
p = 5  # Number of elements to randomly place
values = [1, 2, 3, 4, 5]  # Values to be randomly placed

# Create an empty 2D array
array = np.zeros(shape)

# Randomly place the elements
result = randomly_place_elements(array, p, values)

print(result)


[[0. 0. 0. 0. 3.]
 [0. 0. 2. 0. 0.]
 [0. 0. 0. 0. 0.]
 [5. 1. 0. 0. 0.]
 [0. 0. 0. 4. 0.]]


58. Subtract the mean of each row of a matrix

In [2]:
import numpy as np

# Create a matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calculate the mean of each row
row_means = np.mean(matrix, axis=1)

# Subtract the row means from the matrix
result = matrix - row_means[:, np.newaxis]

print(result)


[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


59. How to sort an array by the nth column?

In [3]:
import numpy as np

# Create an array
array = np.array([[4, 2, 3], [1, 5, 6], [7, 8, 9]])

# Sort the array by the nth column (n=1 in this example)
sorted_array = array[array[:, 1].argsort()]

print(sorted_array)


[[4 2 3]
 [1 5 6]
 [7 8 9]]


60. How to tell if a given 2D array has null columns?

In [4]:
import numpy as np

# Create a 2D array
array = np.array([[1, 2, 0], [4, 0, 6], [7, 8, 9]])

# Check if any column is null
null_columns = np.all(array == 0, axis=0)

print(null_columns)


[False False False]


61. Find the nearest value from a given value in an array

In [5]:
import numpy as np

# Given value
given_value = 5

# Array
array = np.array([1, 3, 6, 9, 12])

# Find the index of the nearest value
nearest_index = (np.abs(array - given_value)).argmin()

# Get the nearest value
nearest_value = array[nearest_index]

print("Nearest value:", nearest_value)


Nearest value: 6


62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

In [6]:
import numpy as np

# Create the arrays
array1 = np.array([[1, 2, 3]])
array2 = np.array([[4], [5], [6]])

# Create an iterator for the arrays
iterator = np.nditer([array1, array2])

# Initialize the sum
sum_result = 0

# Iterate over the arrays and compute the sum
for x, y in iterator:
    sum_result += x + y

print("Sum:", sum_result)


Sum: 63


63. Create an array class that has a name attribute

In [7]:
import numpy as np

class NamedArray(np.ndarray):
    def __new__(cls, input_array, name=None):
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None:
            return
        self.name = getattr(obj, 'name', None)


64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [8]:
import numpy as np

# Given vector
vector = np.array([1, 2, 3, 4, 5])

# Second vector with indices
indices = np.array([0, 1, 3, 1, 4])

# Add 1 to each element indexed by the second vector
np.add.at(vector, indices, 1)

print(vector)


[2 4 3 5 6]


65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

In [9]:
import numpy as np

# Given vector X
X = np.array([1, 2, 3, 4, 5])

# Given array F
F = np.zeros(10)

# Given index list I
I = np.array([2, 4, 1, 3, 2])

# Accumulate elements of X to F based on I
np.add.at(F, I, X)

print(F)


[0. 3. 6. 4. 2. 0. 0. 0. 0. 0.]


66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

In [15]:
import numpy as np

# Define the dimensions of the image
w = 100
h = 100

# Create a random image of dtype ubyte
image = np.random.randint(0, 256, size=(w, h, 3), dtype=np.uint8)

# Reshape the image to a 2D array of shape (w*h, 3)
reshaped_image = image.reshape(-1, 3)

# Compute the number of unique colors
unique_colors = len(np.unique(reshaped_image, axis=0))

print("Number of unique colors:", unique_colors)


Number of unique colors: 9995


67. Considering a four dimensions array, how to get sum over the last two axis at once?

In [14]:
import numpy as np

# four-dimensional array
array = np.random.rand(2, 3, 4, 5)

# Get the sum over the last two axes at once
sum_result = np.sum(array, axis=(-2, -1))

print(sum_result)


[[ 9.73787079 10.07623266  7.84494568]
 [10.50701131 11.70774564  8.14392633]]


Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices?

In [16]:
import numpy as np

# Create the one-dimensional vector D
D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Create the vector S describing subset indices
S = np.array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

# Find the unique subset indices in S
unique_indices = np.unique(S)

# Compute the means of subsets of D using S
subset_means = []
for index in unique_indices:
    subset = D[S == index]
    subset_mean = np.mean(subset)
    subset_means.append(subset_mean)

print("Subset Means:", subset_means)


Subset Means: [5.0, 6.0]


69. How to get the diagonal of a dot product?

In [17]:
import numpy as np

# Create two matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Perform the dot product
dot_product = np.dot(matrix1, matrix2)

# Get the diagonal of the dot product
diagonal = np.diagonal(dot_product)

print(diagonal)


[19 50]


Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [18]:
import numpy as np

# Given vector
vector = np.array([1, 2, 3, 4, 5])

# Build a new vector with 3 consecutive zeros interleaved between each value
new_vector = np.insert(np.repeat(vector, 4), np.arange(3, len(vector)*4, 4), 0)

print(new_vector)


[1 1 1 0 1 2 2 2 0 2 3 3 3 0 3 4 4 4 0 4 5 5 5 0 5]


71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

In [19]:
import numpy as np

# Create the array of dimension (5,5,3)
array1 = np.random.rand(5, 5, 3)

# Create the array with dimensions (5,5)
array2 = np.random.rand(5, 5)

# Multiply the arrays
result = array1 * array2[:, :, np.newaxis]

print(result)


[[[0.54196889 0.35595212 0.57044213]
  [0.15546243 0.1082427  0.14420573]
  [0.33905444 0.31135748 0.12459723]
  [0.85297865 0.24192809 0.89642344]
  [0.03470542 0.1124358  0.12638382]]

 [[0.17750241 0.27130456 0.35335173]
  [0.15419807 0.21004824 0.080361  ]
  [0.14843495 0.46791997 0.40156045]
  [0.33021789 0.30627406 0.5092937 ]
  [0.33371337 0.29895968 0.63779931]]

 [[0.45057355 0.23971265 0.28626128]
  [0.12095122 0.15981361 0.07592904]
  [0.23456382 0.19899557 0.13758978]
  [0.63173808 0.44336468 0.36726844]
  [0.25834643 0.1093277  0.06533334]]

 [[0.53671787 0.42100796 0.29117027]
  [0.47876153 0.50521338 0.24514214]
  [0.49083935 0.65259381 0.61181934]
  [0.70499099 0.60245829 0.09019429]
  [0.11551394 0.80955302 0.21701295]]

 [[0.41767039 0.44688928 0.06723414]
  [0.17337387 0.72002386 0.00520379]
  [0.52595253 0.05440306 0.53801181]
  [0.1731093  0.12453318 0.08620899]
  [0.10291317 0.19216855 0.23613527]]]


72. How to swap two rows of an array?

In [20]:
import numpy as np

# Create an array
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Swap rows 0 and 1
array[[0, 1]] = array[[1, 0]]

print(array)


[[4 5 6]
 [1 2 3]
 [7 8 9]]


73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles

In [21]:
# Set of triplets describing the triangles
triplets = [
    [(0, 0), (1, 1), (2, 0)],
    [(1, 1), (2, 0), (3, 1)],
    [(2, 0), (3, 1), (4, 0)],
    [(3, 1), (4, 0), (5, 1)],
    [(4, 0), (5, 1), (6, 0)],
    [(5, 1), (6, 0), (7, 1)],
    [(6, 0), (7, 1), (8, 0)],
    [(7, 1), (8, 0), (9, 1)],
    [(8, 0), (9, 1), (10, 0)],
    [(9, 1), (10, 0), (11, 1)]
]

# Set to store unique line segments
line_segments = set()

# Iterate over the triplets
for triplet in triplets:
    # Extract line segments from the triplet
    segment1 = (triplet[0], triplet[1])
    segment2 = (triplet[1], triplet[2])
    segment3 = (triplet[2], triplet[0])
    
    # Add line segments to the set
    line_segments.add(segment1)
    line_segments.add(segment2)
    line_segments.add(segment3)

# Print the set of unique line segments
for segment in line_segments:
    print(segment)


((2, 0), (3, 1))
((9, 1), (7, 1))
((9, 1), (10, 0))
((3, 1), (4, 0))
((7, 1), (8, 0))
((7, 1), (5, 1))
((3, 1), (1, 1))
((6, 0), (4, 0))
((8, 0), (6, 0))
((4, 0), (2, 0))
((8, 0), (9, 1))
((0, 0), (1, 1))
((11, 1), (9, 1))
((5, 1), (6, 0))
((5, 1), (3, 1))
((6, 0), (7, 1))
((4, 0), (5, 1))
((2, 0), (0, 0))
((1, 1), (2, 0))
((10, 0), (8, 0))
((10, 0), (11, 1))


74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?

In [22]:
import numpy as np

# Given sorted array C
C = np.array([0, 1, 2, 3, 4, 5])

# Produce array A
A = np.repeat(np.arange(len(C)), C)

print(A)


[1 2 2 3 3 3 4 4 4 4 5 5 5 5 5]


75. How to compute averages using a sliding window over an array?

In [23]:
import numpy as np

def sliding_window_average(array, window_size):
    # Pad the array with zeros on both sides to handle edge cases
    padded_array = np.pad(array, (window_size // 2, window_size // 2), mode='constant')
    
    # Create a sliding window view of the padded array
    sliding_window = np.lib.stride_tricks.sliding_window_view(padded_array, window_size)
    
    # Compute the average along the last axis of the sliding window view
    averages = np.mean(sliding_window, axis=-1)
    
    return averages

# Example usage
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
window_size = 3

averages = sliding_window_average(array, window_size)
print(averages)


[1.         2.         3.         4.         5.         6.
 7.         8.         9.         6.33333333]


76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

In [31]:
import numpy as np

# Create a one-dimensional array Z
Z = np.array([1, 2, 3, 4, 5])

# Build a two-dimensional array with shifted rows
shifted_array = np.lib.stride_tricks.sliding_window_view(Z, 3)

print(shifted_array)


[[1 2 3]
 [2 3 4]
 [3 4 5]]


77. How to negate a boolean, or to change the sign of a float inplace?

In [32]:
boolean_value = True
negated_value = not boolean_value
print(negated_value)


False


78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

In [33]:
import numpy as np

def distance_to_lines(P0, P1, p):
    # Convert points to numpy arrays
    P0 = np.array(P0)
    P1 = np.array(P1)
    p = np.array(p)
    
    # Compute the direction vectors of the lines
    direction_vectors = P1 - P0
    
    # Compute the vector from each line point to the point p
    line_to_point_vectors = p - P0
    
    # Compute the lengths of the direction vectors
    direction_lengths = np.linalg.norm(direction_vectors, axis=1)
    
    # Compute the dot products between the direction vectors and the line-to-point vectors
    dot_products = np.sum(direction_vectors * line_to_point_vectors, axis=1)
    
    # Compute the distances from p to each line
    distances = np.abs(dot_products) / direction_lengths
    
    return distances

# Example usage
P0 = [(1, 1), (2, 2), (3, 3)]
P1 = [(4, 4), (5, 5), (6, 6)]
p = (2, 3)

distances = distance_to_lines(P0, P1, p)
print(distances)


[2.12132034 0.70710678 0.70710678]


79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?

In [34]:
import numpy as np

def distance_to_lines(P0, P1, P):
    # Convert points to numpy arrays
    P0 = np.array(P0)
    P1 = np.array(P1)
    P = np.array(P)
    
    # Compute the direction vectors of the lines
    direction_vectors = P1 - P0
    
    # Compute the vector from each line point to the points in P
    line_to_point_vectors = P[:, np.newaxis] - P0
    
    # Compute the lengths of the direction vectors
    direction_lengths = np.linalg.norm(direction_vectors, axis=1)
    
    # Compute the dot products between the direction vectors and the line-to-point vectors
    dot_products = np.sum(direction_vectors * line_to_point_vectors, axis=2)
    
    # Compute the distances from each point in P to each line
    distances = np.abs(dot_products) / direction_lengths
    
    return distances

# Example usage
P0 = [(1, 1), (2, 2), (3, 3)]
P1 = [(4, 4), (5, 5), (6, 6)]
P = [(2, 3), (4, 5), (6, 7)]

distances = distance_to_lines(P0, P1, P)
print(distances)


[[2.12132034 0.70710678 0.70710678]
 [4.94974747 3.53553391 2.12132034]
 [7.77817459 6.36396103 4.94974747]]


80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)

In [36]:
import numpy as np

def extract_subpart(array, shape, center_element, fill_value):
    # Get the indices of the center element
    center_indices = np.where(array == center_element)
    
    if len(center_indices[0]) == 0:
        raise ValueError("Center element not found in the array")
    
    # Get the coordinates of the center element
    center_coordinates = list(zip(center_indices[0], center_indices[1]))
    
    # Get the top-left corner coordinates of the subpart
    top_left_coordinates = (center_coordinates[0][0] - shape[0] // 2, center_coordinates[0][1] - shape[1] // 2)
    
    # Get the bottom-right corner coordinates of the subpart
    bottom_right_coordinates = (top_left_coordinates[0] + shape[0], top_left_coordinates[1] + shape[1])
    
    # Pad the array if necessary
    padded_array = np.pad(array, ((shape[0] // 2, shape[0] // 2), (shape[1] // 2, shape[1] // 2)), mode='constant', constant_values=fill_value)
    
    # Extract the subpart
    subpart = padded_array[top_left_coordinates[0]:bottom_right_coordinates[0], top_left_coordinates[1]:bottom_right_coordinates[1]]
    
    return subpart


81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

In [37]:
import numpy as np

Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
window_size = 4

R = np.lib.stride_tricks.sliding_window_view(Z, window_size)

print(R)


[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


82. Compute a matrix rank

In [38]:
import numpy as np

# Create your matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Compute the rank of the matrix
rank = np.linalg.matrix_rank(matrix)

print("Matrix Rank:", rank)


Matrix Rank: 2


83. How to find the most frequent value in an array?

In [39]:
import numpy as np

# Create your array
array = np.array([1, 2, 3, 2, 4, 2, 5, 2, 6, 2, 7, 2])

# Find the most frequent value
most_frequent_value = np.bincount(array).argmax()

print("Most frequent value:", most_frequent_value)


Most frequent value: 2


84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

In [40]:
import numpy as np

# Create a random 10x10 matrix
matrix = np.random.randint(0, 10, size=(10, 10))

# Extract all the contiguous 3x3 blocks
blocks = []
for i in range(8):
    for j in range(8):
        block = matrix[i:i+3, j:j+3]
        blocks.append(block)

# Print the extracted blocks
for block in blocks:
    print(block)


[[1 2 2]
 [6 4 1]
 [0 2 9]]
[[2 2 6]
 [4 1 3]
 [2 9 3]]
[[2 6 9]
 [1 3 9]
 [9 3 5]]
[[6 9 4]
 [3 9 4]
 [3 5 7]]
[[9 4 2]
 [9 4 4]
 [5 7 6]]
[[4 2 2]
 [4 4 5]
 [7 6 7]]
[[2 2 9]
 [4 5 7]
 [6 7 0]]
[[2 9 5]
 [5 7 5]
 [7 0 2]]
[[6 4 1]
 [0 2 9]
 [4 6 7]]
[[4 1 3]
 [2 9 3]
 [6 7 6]]
[[1 3 9]
 [9 3 5]
 [7 6 1]]
[[3 9 4]
 [3 5 7]
 [6 1 0]]
[[9 4 4]
 [5 7 6]
 [1 0 9]]
[[4 4 5]
 [7 6 7]
 [0 9 9]]
[[4 5 7]
 [6 7 0]
 [9 9 6]]
[[5 7 5]
 [7 0 2]
 [9 6 4]]
[[0 2 9]
 [4 6 7]
 [5 4 8]]
[[2 9 3]
 [6 7 6]
 [4 8 4]]
[[9 3 5]
 [7 6 1]
 [8 4 8]]
[[3 5 7]
 [6 1 0]
 [4 8 1]]
[[5 7 6]
 [1 0 9]
 [8 1 7]]
[[7 6 7]
 [0 9 9]
 [1 7 4]]
[[6 7 0]
 [9 9 6]
 [7 4 7]]
[[7 0 2]
 [9 6 4]
 [4 7 5]]
[[4 6 7]
 [5 4 8]
 [0 6 1]]
[[6 7 6]
 [4 8 4]
 [6 1 2]]
[[7 6 1]
 [8 4 8]
 [1 2 1]]
[[6 1 0]
 [4 8 1]
 [2 1 3]]
[[1 0 9]
 [8 1 7]
 [1 3 9]]
[[0 9 9]
 [1 7 4]
 [3 9 2]]
[[9 9 6]
 [7 4 7]
 [9 2 3]]
[[9 6 4]
 [4 7 5]
 [2 3 2]]
[[5 4 8]
 [0 6 1]
 [1 8 5]]
[[4 8 4]
 [6 1 2]
 [8 5 5]]
[[8 4 8]
 [1 2 1]
 [5 5 3]]
[[4 8 1]
 [2 1 3]
 [

85. Create a 2D array subclass such that Z[i,j] == Z[j,i]

In [41]:
import numpy as np

class SymmetricArray(np.ndarray):
    def __new__(cls, input_array):
        obj = np.asarray(input_array).view(cls)
        return obj
    
    def __setitem__(self, index, value):
        i, j = index
        super().__setitem__((i, j), value)
        super().__setitem__((j, i), value)


86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))

In [42]:
import numpy as np

# Set the number of matrices and their shape
p = 3
n = 4

# Create p matrices with shape (n,n)
matrices = [np.random.rand(n, n) for _ in range(p)]

# Create p vectors with shape (n,1)
vectors = [np.random.rand(n, 1) for _ in range(p)]

# Compute the sum of the p matrix products
result = np.sum([np.dot(matrix, vector) for matrix, vector in zip(matrices, vectors)], axis=0)

print(result)


[[2.22824027]
 [2.66852414]
 [2.36272143]
 [2.53372885]]


87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

In [43]:
import numpy as np

# Create a 16x16 array
array = np.random.randint(0, 10, size=(16, 16))

# Reshape the array into blocks of size 4x4
blocks = array.reshape(4, 4, 4, 4)

# Compute the sum of each block
block_sums = np.sum(blocks, axis=(2, 3))

print(block_sums)


[[71 67 74 80]
 [62 73 77 57]
 [46 78 63 49]
 [80 44 50 83]]


89. How to get the n largest values of an array

In [46]:
import numpy as np

# Create your array
array = np.array([5, 2, 9, 1, 7, 3, 8, 4, 6])

# Specify the value of n
n = 3

# Get the n largest values
largest_values = np.partition(array, -n)[-n:]

print("Largest values:", largest_values)


Largest values: [7 8 9]


90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)

In [45]:
import itertools

# Define the vectors
vector1 = [1, 2, 3]
vector2 = [4, 5]
vector3 = [6, 7, 8]

# Build the cartesian product
cartesian_product = list(itertools.product(vector1, vector2, vector3))

print(cartesian_product)


[(1, 4, 6), (1, 4, 7), (1, 4, 8), (1, 5, 6), (1, 5, 7), (1, 5, 8), (2, 4, 6), (2, 4, 7), (2, 4, 8), (2, 5, 6), (2, 5, 7), (2, 5, 8), (3, 4, 6), (3, 4, 7), (3, 4, 8), (3, 5, 6), (3, 5, 7), (3, 5, 8)]


91. How to create a record array from a regular array?

In [48]:
import numpy as np

# Create a regular array
regular_array = np.array([(1, 'Alice', 25), (2, 'Bob', 30), (3, 'Charlie', 35)])

# Define the dtype for the record array
dtype = [('ID', int), ('Name', 'U10'), ('Age', int)]

# Create the record array
record_array = np.rec.array(regular_array)

print(record_array)


[['1' 'Alice' '25']
 ['2' 'Bob' '30']
 ['3' 'Charlie' '35']]


92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods

In [49]:
# Method 1: Using np.power()
Z_cubed_method1 = np.power(Z, 3)
     

# Method 2: Using the exponentiation operator **
Z_cubed_method2 = Z ** 3
     

# Method 3: Using element-wise multiplication
Z_cubed_method3 = Z * Z * Z

93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

In [ ]:
import numpy as np

# Create arrays A and B
A = np.random.randint(0, 10, size=(8, 3))
B = np.random.randint(0, 10, size=(2, 2))

# Find rows of A that contain elements of each row of B
matching_rows = []
for row in B:
    matching_rows.extend(np.where((A == row[:, None]).all(axis=2))[0])

# Remove duplicate rows
matching_rows = np.unique(matching_rows)

print("Matching rows:", matching_rows)


94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

In [51]:
import numpy as np

# Create a 10x3 matrix
matrix = np.random.randint(0, 5, size=(10, 3))

# Extract rows with unequal values
unequal_rows = matrix[np.any(matrix[:, 1:] != matrix[:, :-1], axis=1)]

print(unequal_rows)


[[3 2 0]
 [4 2 0]
 [0 3 2]
 [3 1 3]
 [3 1 4]
 [4 3 4]
 [2 3 1]
 [2 3 0]
 [0 0 1]
 [1 4 3]]


95. Convert a vector of ints into a matrix binary representation

In [60]:
import numpy as np

# Create a vector of integers
vector = np.array([1, 2, 3, 4, 5])

# Convert the vector into a matrix binary representation
binary_matrix = np.unpackbits(vector[:, np.newaxis].view(np.uint8), axis=1)

print(binary_matrix)


[[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


96. Given a two dimensional array, how to extract unique rows?

In [61]:
import numpy as np

# Create a two-dimensional array
array = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3], [7, 8, 9]])

# Extract unique rows
unique_rows = np.unique(array, axis=0)

print(unique_rows)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

In [64]:
import numpy as np
# Create two vectors A and B
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# Einsum equivalent of inner product
inner_product = np.einsum('i,i', A, B)

# Einsum equivalent of outer product
outer_product = np.einsum('i,j->ij', A, B)

# Einsum equivalent of sum
sum_result = np.einsum('i', A)

# Einsum equivalent of element-wise multiplication
mul_result = np.einsum('i,i->i', A, B)

print("Inner product:", inner_product)
print("Outer product:\n", outer_product)
print("Sum:", sum_result)
print("Element-wise multiplication:", mul_result)


Inner product: 32
Outer product:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Sum: [1 2 3]
Element-wise multiplication: [ 4 10 18]


98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples

In [67]:
import numpy as np

# Define the X and Y vectors that describe the path
X = np.array([1, 2, 3, 4, 5])
Y = np.array([2, 4, 6, 8, 10])

# Define the number of equidistant samples
num_samples = 10

# Compute the total length of the path
path_length = np.sum(np.sqrt(np.diff(X)**2 + np.diff(Y)**2))

# Compute the step size for equidistant sampling
step_size = path_length / (num_samples - 1)

# Compute the cumulative distance along the path
cumulative_distance = np.cumsum(np.sqrt(np.diff(X)**2 + np.diff(Y)**2))
cumulative_distance = np.insert(cumulative_distance, 0, 0)

# Interpolate the path using equidistant samples
sampled_X = np.interp(np.linspace(0, cumulative_distance[-1], num_samples), cumulative_distance, X)
sampled_Y = np.interp(np.linspace(0, cumulative_distance[-1], num_samples), cumulative_distance, Y)

# Print the sampled X and Y coordinates
print("Sampled X:", sampled_X)
print("Sampled Y:", sampled_Y)


Sampled X: [1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
Sampled Y: [ 2.          2.88888889  3.77777778  4.66666667  5.55555556  6.44444444
  7.33333333  8.22222222  9.11111111 10.        ]


99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n

In [69]:
import numpy as np

def select_multinomial_rows(n, X):
    # Find the rows that contain only integers
    integer_rows = np.all(X.astype(int) == X, axis=1)
    
    # Find the rows that sum to n
    sum_rows = np.sum(X, axis=1) == n
    
    # Select the rows that satisfy both conditions
    selected_rows = X[integer_rows & sum_rows]
    
    return selected_rows

# Example usage
n = 10
X = np.array([[1, 2, 7], [3, 4, 3], [5, 5, 0], [2, 3, 5]])

selected_rows = select_multinomial_rows(n, X)
print(selected_rows)


[[1 2 7]
 [3 4 3]
 [5 5 0]
 [2 3 5]]


100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).

In [70]:
import numpy as np

def bootstrap_mean_confidence_interval(X, N, alpha=0.05):
    # Initialize an array to store the means of the bootstrap samples
    bootstrap_means = np.empty(N)
    
    # Perform bootstrapping
    for i in range(N):
        # Resample the array with replacement
        resampled_X = np.random.choice(X, size=len(X), replace=True)
        
        # Compute the mean of the resampled array
        bootstrap_means[i] = np.mean(resampled_X)
    
    # Compute the lower and upper percentiles of the bootstrap means
    lower_percentile = (alpha / 2) * 100
    upper_percentile = (1 - alpha / 2) * 100
    lower_bound = np.percentile(bootstrap_means, lower_percentile)
    upper_bound = np.percentile(bootstrap_means, upper_percentile)
    
    return lower_bound, upper_bound

# Example usage
X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
N = 1000
alpha = 0.05

lower_bound, upper_bound = bootstrap_mean_confidence_interval(X, N, alpha)
print("Bootstrapped 95% Confidence Interval for the Mean:", (lower_bound, upper_bound))


Bootstrapped 95% Confidence Interval for the Mean: (3.7, 7.2)
