Import the numpy package under the name np

In [1]:
import numpy as np


Print the numpy version and the configuration

In [2]:
import numpy as np

print("Numpy Version:", np.__version__)
print("Numpy Configuration:")
print(np.show_config())


Numpy Version: 1.26.2
Numpy Configuration:
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30153",
      "commands": "cl.exe"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.0",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30153",
      "commands": "cl.exe"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "mkl-sdl",
      "found": true,
      "version": "2023.1",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/Administrator/miniconda3/envs/arewadatascience/Library/include",
      "lib directory": "C:/Use

c:\Users\Administrator\miniconda3\envs\arewadatascience\Lib\site-packages\numpy\__config__.py:149: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


Create a null vector of size 10

In [4]:
import numpy as np

n_vector = np.zeros(10)
print(n_vector)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


How to find the memory size of any array

In [5]:
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Find the memory size
memory_size = arr.nbytes

print("Memory size of the array:", memory_size, "bytes")


Memory size of the array: 20 bytes


How to get the documentation of the numpy add function from the command line?

Create a null vector of size 10 but the fifth value which is 1

In [6]:
import numpy as np

null_vector = np.zeros(10)
null_vector[4] = 1

print(null_vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Create a vector with values ranging from 10 to 49

In [7]:
import numpy as np

vector = np.arange(10, 50)
print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


 Reverse a vector (first element becomes last)

In [8]:
reversed_vector = vector[::-1]
print(reversed_vector)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
import numpy as np

matrix = np.arange(9).reshape(3, 3)
print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


Find indices of non-zero elements from [1,2,0,0,4,0]

In [2]:
import numpy as np

'''arr=np.array([1,2,0,0,4,0])
print("Elements of array arr is:",arr )
print("Is array arr contains non-zero elements:" ,np.any(arr))'''

arr=np.array([1,2,0,0,4,0])
print("Elements of array arr is:",arr )
No_zero_ele =np.nonzero(arr)
print("Non-zero elements of the array arr:",arr[np.nonzero(arr)])
print("indices non-zero elements of array arr:",No_zero_ele )

Elements of array arr is: [1 2 0 0 4 0]
Non-zero elements of the array arr: [1 2 4]
indices non-zero elements of array arr: (array([0, 1, 4], dtype=int64),)


Create a 3x3 identity matrix

In [3]:
import numpy as np

i_matrix = np.eye(3)
print(i_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Create a 3x3x3 array with random values

In [5]:
import numpy as np

arr = np.random.rand(3, 3, 3)
print(arr)


[[[0.12693413 0.49381772 0.04902207]
  [0.14062798 0.43269522 0.58320315]
  [0.92643806 0.97569955 0.51996709]]

 [[0.69411651 0.55679996 0.65688005]
  [0.84072972 0.76573622 0.38932305]
  [0.74551745 0.77215531 0.61292318]]

 [[0.16976265 0.06451953 0.67512418]
  [0.43375784 0.72108509 0.83981372]
  [0.16351687 0.53004099 0.34410989]]]


Create a 10x10 array with random values and find the minimum and maximum values

In [8]:
import numpy as np

# Create a 10x10 array with random values
arr = np.random.rand(10, 10)
print(arr)

# Find the minimum and maximum values
min_value = np.min(arr)
max_value = np.max(arr)

print("Minimum value:", min_value)
print("Maximum value:", max_value)


[[0.30526894 0.11639061 0.63892729 0.84632996 0.04858464 0.78900305
  0.55692008 0.87444174 0.03702647 0.89019205]
 [0.33570597 0.79614245 0.90859058 0.43514676 0.97324435 0.76157976
  0.09068936 0.22616824 0.89306922 0.77791367]
 [0.20767048 0.74043809 0.59123003 0.65211408 0.47519938 0.23625395
  0.60022452 0.56525003 0.04564811 0.01744112]
 [0.43761889 0.91169507 0.64375808 0.18724672 0.9960855  0.56424763
  0.91261412 0.14024963 0.63456674 0.09960344]
 [0.24756833 0.37806268 0.39446677 0.11076914 0.43354331 0.10507483
  0.0545226  0.70654062 0.89691784 0.10522198]
 [0.32738225 0.53747775 0.62625242 0.21709438 0.840725   0.8490383
  0.68669582 0.96042351 0.65909543 0.18841251]
 [0.43832431 0.76557281 0.90722116 0.55625866 0.28481037 0.48324952
  0.30190915 0.48695104 0.94117468 0.66853657]
 [0.98927147 0.54239301 0.89316984 0.02664668 0.81505523 0.97901721
  0.12080957 0.50349604 0.68600126 0.22699601]
 [0.64869657 0.66650226 0.0409895  0.23673672 0.85679195 0.62440313
  0.85946891 

Create a random vector of size 30 and find the mean value

In [9]:
import numpy as np

# Create a random vector of size 30
random_vector = np.random.rand(30)

# Find the mean value
mean_value = np.mean(random_vector)

print("Mean value:", mean_value)


Mean value: 0.49129532652075386


15. Create a 2d array with 1 on the border and 0 inside

In [31]:
import numpy as np


arr = np.ones((5,5))
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

print(arr)


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


16. How to add a border (filled with 0's) around an existing array?

In [33]:
import numpy as np

# Existing array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Add border filled with 0's
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

print(arr)


[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


17. What is the result of the following expression?

In [37]:
import numpy as np
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [45]:
import numpy as np

m = np.diag([1, 2, 3, 4], k=-1)
print(m)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


Create a 8x8 matrix and fill it with a checkerboard pattern

In [48]:
import numpy as np

mt = np.zeros((8, 8))
mt[1::2, ::2] = 1
mt[::2, 1::2] = 1

print(mt)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [49]:
import numpy as np

shape = (6, 7, 8)
index_100 = np.unravel_index(99, shape)

print("Index (x, y, z) of the 100th element:", index_100)


Index (x, y, z) of the 100th element: (1, 5, 3)


Create a checkerboard 8x8 matrix using the tile function

In [53]:
import numpy as np


tile = np.array([[0, 1], [1, 0]])
cb = np.tile(tile, (4, 4))

print(cb)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Normalize a 5x5 random matrix

In [3]:
from sklearn.preprocessing import normalize
import numpy as np

# Create a 5x5 random matrix
matrix = np.random.rand(5, 5)

# Normalize the matrix
normalized_matrix = normalize(matrix)

print(normalized_matrix)


[[0.75660908 0.43914236 0.16413115 0.13390694 0.43569093]
 [0.51145843 0.4040846  0.59026309 0.44783991 0.16172449]
 [0.42105228 0.3640624  0.5457537  0.59907741 0.18284612]
 [0.6047449  0.09698108 0.34175996 0.50622042 0.50181599]
 [0.12699218 0.69766917 0.43548413 0.39209633 0.39210299]]


Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [3]:
import numpy as np

# Create the custom dtype
color_dtype = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])

# Example usage
color = np.array([(255, 0, 0, 255)], dtype=color_dtype)
print(color)


[(255, 0, 0, 255)]


24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [5]:
import numpy as np

mx1 = np.random.rand(5, 3)
mx2 = np.random.rand(3, 2)
result = np.dot(mx1, mx2)

print(result)


[[1.42617001 1.24193318]
 [1.34788184 1.47911396]
 [1.34292602 1.19240974]
 [0.46256623 0.50611363]
 [1.06061382 1.24235962]]


25. Given a 1D array, negate all elements which are between 3 and 8, in place

In [10]:
import numpy as np


arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr[(arr > 3) & (arr < 8)] *= -1

print(arr)


[ 1  2  3 -4 -5 -6 -7  8  9 10]


In [11]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


27. Consider an integer vector Z, which of these expressions are legal?.\
Z**Z.\
2 << Z >> 2.\
Z <- Z.\
1j*Z.\
Z/1/1.\
Z<Z>Z

'''The following expressions are not legal:.\

2 << Z >> 2: The left shift and right shift operators (<< and >>) are not defined for arrays or vectors..\
1j * Z: The complex multiplication operator (*) is not defined for arrays or vectors.'''

1.  What are the result of the following expressions?.\
np.array(0) / np.array(0).\
np.array(0) // np.array(0).\
np.array([np.nan]).astype(int).astype(float)

In [3]:
import numpy as np

print('The result of the expressions are:')
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

The result of the expressions are:


C:\Users\Administrator\AppData\Local\Temp\ipykernel_10476\2426853172.py:4: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_10476\2426853172.py:5: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_10476\2426853172.py:6: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])

29. How to round away from zero a float array ?

In [5]:
import numpy as np

f_array = np.array([-1.5, -1.2, -0.8, 0.8, 1.2, 1.5])
r_array = np.ceil(f_array)

print(r_array)


[-1. -1. -0.  1.  2.  2.]


30. How to find common values between two arrays?

In [6]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])
common_values = np.intersect1d(array1, array2)

print("Common values:", common_values)


Common values: [4 5]


1.  Is the following expressions true?.\
np.sqrt(-1) == np.emath.sqrt(-1)

In [8]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_10476\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

33. How to get the dates of yesterday, today and tomorrow?

In [9]:
import datetime

# Get today's date
today = datetime.date.today()

# Get yesterday's date
yesterday = today - datetime.timedelta(days=1)

# Get tomorrow's date
tomorrow = today + datetime.timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2024-02-07
Today: 2024-02-08
Tomorrow: 2024-02-09


34. How to get all the dates corresponding to the month of July 2016?

In [10]:
import pandas as pd

# Create a date range for the month of July 2016
dates = pd.date_range(start='2016-07-01', end='2016-07-31')

print(dates)


DatetimeIndex(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
               '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
               '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
               '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
               '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
               '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
               '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
               '2016-07-29', '2016-07-30', '2016-07-31'],
              dtype='datetime64[ns]', freq='D')


36. Extract the integer part of a random array of positive numbers using 4 different methods

In [20]:
import numpy as np

# Create a random array of positive numbers
random_array = np.random.rand(5) * 10

# Extract the integer part using astype() method
integer_part = random_array.astype(int)

print(integer_part)


[3 8 4 0 3]


In [19]:
import numpy as np

# Create a random array of positive numbers
random_array = np.random.rand(5) * 10

# Extract the integer part using the floor method
integer_part = np.floor(random_array)

print(integer_part)


[0. 1. 4. 1. 8.]


In [21]:
import numpy as np

# Create a random array of positive numbers
random_array = np.random.rand(5) * 10

# Extract the integer part using the trunc function
integer_part = np.trunc(random_array)

print(integer_part)



[0. 4. 3. 8. 2.]


In [22]:
import numpy as np

# Create a random array of positive numbers
random_array = np.random.rand(5) * 10

# Extract the integer part using np.int function
integer_part = np.int_(random_array)

print(integer_part)


[1 1 5 8 8]


37. Create a 5x5 matrix with row values ranging from 0 to 4

In [23]:
import numpy as np

matrix = np.tile(np.arange(5), (5, 1))
print(matrix)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


38. Consider a generator function that generates 10 integers and use it to build an array

In [24]:
import numpy as np

# Define the generator function
def generate_integers():
    for i in range(10):
        yield i

# Build an array using the generator function
array = np.fromiter(generate_integers(), dtype=int)

print(array)


[0 1 2 3 4 5 6 7 8 9]


39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [28]:
import numpy as np

vector = np.linspace(0, 1, 12)[1:-1]
print(vector)


[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


40. Create a random vector of size 10 and sort it

In [29]:
import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

# Sort the vector
sorted_vector = np.sort(random_vector)

print(sorted_vector)


[0.08054443 0.18523198 0.38139533 0.38690612 0.44043328 0.48004155
 0.60746102 0.82010404 0.82664286 0.88184955]


How to sum a small array faster than np.sum?

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
sum_result = sum(arr)

print("Sum:", sum_result)


Sum: 15


42. Consider two random array A and B, check if they are equal

In [2]:
import numpy as np

# Create two random arrays
A = np.random.rand(5)
B = np.random.rand(5)

# Check if the arrays are equal
equal = np.array_equal(A, B)

print("Are the arrays equal?", equal)


Are the arrays equal? False


43. Make an array immutable (read-only)

In [7]:
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Make the array read-only
arr.flags.writeable = False

# Try to modify the array (will raise an error)
arr[0] = 10


44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [8]:
import numpy as np

# Create a random 10x2 matrix representing cartesian coordinates
cartesian_coords = np.random.rand(10, 2)

# Convert cartesian coordinates to polar coordinates
x = cartesian_coords[:, 0]
y = cartesian_coords[:, 1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)

# Create a 10x2 matrix representing polar coordinates
polar_coords = np.column_stack((r, theta))

print("Cartesian Coordinates:")
print(cartesian_coords)
print("\nPolar Coordinates:")
print(polar_coords)


Cartesian Coordinates:
[[0.03860662 0.57961299]
 [0.51768089 0.19846126]
 [0.04857541 0.56912631]
 [0.94411919 0.1555117 ]
 [0.93782122 0.56062358]
 [0.20349283 0.93845465]
 [0.07333724 0.55350739]
 [0.94599581 0.33043552]
 [0.70775503 0.22946506]
 [0.36571109 0.59332849]]

Polar Coordinates:
[[0.58089732 1.50428698]
 [0.55441896 0.36608501]
 [0.57119553 1.48565183]
 [0.95684112 0.1632503 ]
 [1.09261495 0.53879562]
 [0.96026375 1.35726383]
 [0.55834468 1.43906808]
 [1.00204576 0.33605031]
 [0.74402379 0.31352206]
 [0.69698156 1.01842547]]


45. Create random vector of size 10 and replace the maximum value by 0

In [10]:
import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

# Find the maximum value
max_value = np.max(random_vector)

# Replace the maximum value with 0
random_vector[random_vector == max_value] = 0

print(random_vector)


[0.40610465 0.47006855 0.08662248 0.         0.74982152 0.16660943
 0.04631832 0.61444527 0.8087169  0.36575479]


46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area

In [12]:
import numpy as np

# Create a structured array with x and y coordinates
coordinates = np.zeros((10,), dtype=[('x', float), ('y', float)])

# Generate x and y coordinates covering the [0,1]x[0,1] area
coordinates['x'] = np.linspace(0, 1, 10)
coordinates['y'] = np.linspace(0, 1, 10)

print(coordinates)


[(0.        , 0.        ) (0.11111111, 0.11111111)
 (0.22222222, 0.22222222) (0.33333333, 0.33333333)
 (0.44444444, 0.44444444) (0.55555556, 0.55555556)
 (0.66666667, 0.66666667) (0.77777778, 0.77777778)
 (0.88888889, 0.88888889) (1.        , 1.        )]


47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [13]:
import numpy as np

# Example arrays
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

# Construct the Cauchy matrix
C = 1 / (X[:, np.newaxis] - Y)

print(C)


[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


48. Print the minimum and maximum representable value for each numpy scalar type

In [ ]:
import numpy as np

# List of numpy scalar types
scalar_types = [np.bool_, np.int8, np.int16, np.int32, np.int64, np.uint8, np.uint16, np.uint32, np.uint64,
                np.float16, np.float32, np.float64, np.complex64, np.complex128]

# Iterate over the scalar types and print the minimum and maximum values
for scalar_type in scalar_types:
    min_value = np.iinfo(scalar_type).min if np.issubdtype(scalar_type, np.integer) else np.finfo(scalar_type).min
    max_value = np.iinfo(scalar_type).max if np.issubdtype(scalar_type, np.integer) else np.finfo(scalar_type).max
    print(f"{scalar_type.__name__}: Minimum = {min_value}, Maximum = {max_value}")


49. How to print all the values of an array?

In [16]:
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Print all the values of the array
print(arr)


[1 2 3 4 5]


50. How to find the closest value (to a given scalar) in a vector?

In [17]:
import numpy as np

# Given scalar
scalar = 3.5

# Vector
vector = np.array([1, 2, 3, 4, 5])

# Calculate the absolute difference
abs_diff = np.abs(vector - scalar)

# Find the index of the element with the smallest absolute difference
closest_index = np.argmin(abs_diff)

# Get the closest value
closest_value = vector[closest_index]

print("Closest value:", closest_value)


Closest value: 3
